name: 安卓定时执行POST请求

# 触发条件：每5分钟一次，同时允许手动触发
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟执行一次

# 工作流权限设置
permissions:
  contents: read  # 仅需要读取代码的权限

jobs:
  post-request:
    runs-on: ubuntu-latest
    name: 发送POST请求
    timeout-minutes: 5  # 任务超时时间
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 只拉取最新提交，加快速度
      
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'  # 缓存pip依赖，加快安装速度
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
        id: install-deps  # 步骤ID，便于日志定位
      
      - name: 运行POST请求脚本
        env:
          AZID: ${{ secrets.AZID }}  # 从secrets获取AZID变量
          PYTHONUNBUFFERED: 1  # 确保日志实时输出
        run: |
          echo "开始执行POST请求脚本..."
          python post_request.py
        id: run-script
      
      - name: 任务执行结果
        if: always()  # 无论前面步骤是否成功都执行
        run: |
          if [ "${{ steps.run-script.outcome }}" = "success" ]; then
            echo "任务执行成功"
          else
            echo "任务执行失败"
            exit 1  # 标记工作流失败
          fi
    
