name: 自动签到

# 触发条件：手动触发和每天北京时间6点
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 22 * * *'  # UTC时间22点 = 北京时间6点（UTC+8）

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: 执行签到
        env:
          # 从GitHub Secrets获取多个session3rd，用逗号分隔
          SESSION3RDS: ${{ secrets.SESSION3RDS }}
        run: python checkin.py
