name: 安卓定时打卡任务

# 触发条件：每天北京时间6点自动运行，同时支持手动触发
on:
  schedule:
    # UTC时间比北京时间晚8小时，所以北京时间6点对应UTC时间22点
    - cron: '0 22 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  punch:
    runs-on: ubuntu-latest
    
    steps:
      - name:  checkout代码
        uses: actions/checkout@v4
      
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: 执行打卡脚本
        env:
          # 从GitHub Secrets中获取session3rd值，命名为azid
          AZID: ${{ secrets.AZID }}
        run: |
          python - <<END
import requests
import os

url = "https://api.planet.shenxu.net.cn/planet/api/client/punch/dates"
headers = {
  "sign": "58527e8627e57e37ffe5b17d9a60c12c",  # 直接写入sign值
  "user-agent": "Mozilla/5.0 (Linux; Android 14; M2102K1C Build/UKQ1.240624.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.168 Mobile Safari/537.36 uni-app Html5Plus/1.0 (Immersed/39.142857)",
  "Content-Type": "application/x-www-form-urlencoded",
  "Host": "api.planet.shenxu.net.cn",
  "Connection": "Keep-Alive",
  "Accept-Encoding": "gzip"
}

# 使用环境变量中的azid作为session3rd的值
data = f"scene=0&version=1.1.11&session3rd={os.getenv('AZID')}"

try:
    res = requests.post(url, headers=headers, data=data)
    print(f"响应状态码: {res.status_code}")
    print(f"响应内容: {res.text}")
    res.raise_for_status()  # 如果响应状态码不是200，会抛出异常
except Exception as e:
    print(f"请求失败: {str(e)}")
    exit(1)
END
      
      - name: 输出结果
        if: always()
        run: echo "打卡任务已执行"
    
